apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::928887033198:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::928887033198:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1RSHZTXEBBB6C
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-04-28T07:47:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1407"
  uid: d9b1656c-bd70-4429-868f-6c80dfff7419
